/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
 * Generated on: 28-Dec-2025 13:02:17
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 51
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,17 -> [-2.500000e-01 2.500000e-01)
 * Input             : s16,12 -> [-8 8)
 * Filter Internals  : Specify Precision
 *   Output          : s16,12 -> [-8 8)
 *   Product         : s31,28 -> [-4 4)
 *   Accumulator     : s31,28 -> [-4 4)
 *   Round Mode      : convergent
 *   Overflow Mode   : saturate
 */

/* General type conversion for MATLAB generated C-code  */
#include "C:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int coeffLen = 51;
const int16_T coeff[51] = {
      -33,   -115,   -209,   -342,   -453,   -510,   -456,   -266,     52,
      437,    784,    963,    861,    424,   -300,  -1153,  -1878,  -2180,
    -1797,   -582,   1434,   4024,   6792,   9258,  10961,  11568,  10961,
     9258,   6792,   4024,   1434,   -582,  -1797,  -2180,  -1878,  -1153,
     -300,    424,    861,    963,    784,    437,     52,   -266,   -456,
     -510,   -453,   -342,   -209,   -115,    -33
};
